/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cliente;

import controller.ControllerCliente;
import facade.FacadeJpa;
import java.util.List;
import javax.swing.JOptionPane;
import model.Cliente;
import util.CheckDefaultTableModel;
import util.Internal;
import util.MyDefaultTableModel;
import util.Texto;
import view.venda.ViewNovaVenda;

/**
 *
 * @author paulosouza
 */
public class ViewConsultaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaCliente
     */
    private MyDefaultTableModel tableModel;
    private Cliente cliente = new Cliente();

    public ViewConsultaCliente() {
        initComponents();
        Internal.retiraBotao(this);
        recarregarTabela();
    }

    public void iniciarTabela() {
        tableModel = new MyDefaultTableModel(new String[]{"Nome", "Endereço", "Número", "Telefone"}, 0, false);
        jTableCliente.setModel(tableModel);
    }

    public void preencherTabela(List<Cliente> listCliente) {

        for (int i = 0; i < listCliente.size(); i++) {
            String[] linhas = new String[]{
                listCliente.get(i).getNome(),
                listCliente.get(i).getEndereco(),
                String.valueOf(listCliente.get(i).getNumerocasa()),
                String.valueOf(listCliente.get(i).getTelefone())
            };
            tableModel.addRow(linhas);
        }
        jTableCliente.setModel(tableModel);

    }

    public void recarregarTabela() {
        iniciarTabela();
        preencherTabela(FacadeJpa.getInstance().getCliente().selectAllCliente());
        jTextFieldNomeBuscar.setText("");
    }

    public void buscarDigitado(String clienteNome) {
        iniciarTabela();
        preencherTabela(FacadeJpa.getInstance().getCliente().findByNomeList(clienteNome));

    }

    public void editarCliente() {

        ViewNovoCliente viewNovoCliente = new ViewNovoCliente(null, true);
        viewNovoCliente.editarCliente(getCliente());
        viewNovoCliente.setVisible(true);
    }
    
    

    public Cliente getCliente()
    {
        return FacadeJpa.getInstance().getCliente().findByNomeSingle(Texto.getLinhaTable(jTableCliente, 0));
    }

    public boolean excluirCliente()
    {
        boolean excluir = false;
        ControllerCliente controllerCliente = new ControllerCliente();
        excluir = controllerCliente.excluir(getCliente());

        if (excluir)
            return true;
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jButtonNovoCliente = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeBuscar = new javax.swing.JTextField();
        jButtonRecarregar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        jTableCliente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        jButtonNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novoCliente.png"))); // NOI18N
        jButtonNovoCliente.setText("Novo Cliente");
        jButtonNovoCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonNovoClienteActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar Cliente:");

        jTextFieldNomeBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNomeBuscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldNomeBuscarActionPerformed(evt);
            }
        });

        jButtonRecarregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh3.png"))); // NOI18N
        jButtonRecarregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRecarregarActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNovoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomeBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRecarregar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRecarregar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldNomeBuscar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonNovoCliente)
                    .addComponent(jButtonEditar))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoClienteActionPerformed
        ViewNovoCliente viewNovoCliente = new ViewNovoCliente(null, true);
        viewNovoCliente.cadastrarNovoCliente();
        viewNovoCliente.setVisible(true);
        recarregarTabela();
    }//GEN-LAST:event_jButtonNovoClienteActionPerformed

    private void jButtonRecarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecarregarActionPerformed
        recarregarTabela();
    }//GEN-LAST:event_jButtonRecarregarActionPerformed

    private void jTextFieldNomeBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeBuscarActionPerformed
        buscarDigitado(jTextFieldNomeBuscar.getText());
    }//GEN-LAST:event_jTextFieldNomeBuscarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        if (jTableCliente.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente na tabela.");
            return;
        }
        editarCliente();
        recarregarTabela();

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonExcluirActionPerformed
    {//GEN-HEADEREND:event_jButtonExcluirActionPerformed
        if(jTableCliente.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Selecione um cliente.");
        }
        if (excluirCliente())
            JOptionPane.showMessageDialog(null, "Excluído com sucesso.");
        else JOptionPane.showMessageDialog(null, "Erro ao excluir.");

        recarregarTabela();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableClienteMouseClicked
    {//GEN-HEADEREND:event_jTableClienteMouseClicked
        if (evt.getClickCount() >= 2) {
            
            ViewNovaVenda viewNovaVenda = new ViewNovaVenda(null, true);
            cliente = FacadeJpa.getInstance().getCliente().findByNomeSingle(Texto.getLinhaTable(jTableCliente, 0));
            viewNovaVenda.novaVenda(cliente);
            viewNovaVenda.setVisible(true);
        }
    }//GEN-LAST:event_jTableClienteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovoCliente;
    private javax.swing.JButton jButtonRecarregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextFieldNomeBuscar;
    // End of variables declaration//GEN-END:variables
}
